<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/data_processing1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Removing NaN values: ```.dropna()```

In [1]:
import pandas as pd

In [2]:
# Creating a df
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv')
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [3]:
# cheking NaN values
df.isna()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,False,False,False,False,False,False,False,True,False,False
1,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...
56,False,False,False,False,False,False,False,False,False,False
57,False,False,False,True,False,True,False,False,False,False
58,False,False,False,False,True,False,False,False,True,False
59,False,False,False,False,False,True,False,False,False,False
60,False,False,False,False,False,False,False,True,False,False

In [4]:
df.isna().sum()

index                0
company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [6]:
df.isna().sum() / len(df) * 100

index                0.000000
company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [9]:
# number of rows
len(df)

61

In [8]:
# removing rows with a nan value
len(df.dropna())

14

In [12]:
# number of columns
len(df.columns)

10

In [13]:
# removing columns with a nan value
df.dropna(axis=1)

    index      company   body-style num-of-cylinders
0       0  alfa-romero  convertible             four
1       1  alfa-romero  convertible             four
2       2  alfa-romero    hatchback              six
3       3         audi        sedan             four
4       4         audi        sedan             five
..    ...          ...          ...              ...
56     81   volkswagen        sedan             four
57     82   volkswagen        sedan             four
58     86   volkswagen        sedan             four
59     87        volvo        sedan             four
60     88        volvo        wagon             four

[61 rows x 4 columns]

In [14]:
# number of columns after removal
len(df.dropna(axis=1).columns)

4

In [25]:
# setting a threshold
df.dropna(axis=1, thresh=50)

    index      company   body-style num-of-cylinders    price
0       0  alfa-romero  convertible             four  13495.0
1       1  alfa-romero  convertible             four  16500.0
2       2  alfa-romero    hatchback              six  16500.0
3       3         audi        sedan             four  13950.0
4       4         audi        sedan             five  17450.0
..    ...          ...          ...              ...      ...
56     81   volkswagen        sedan             four   7975.0
57     82   volkswagen        sedan             four   7995.0
58     86   volkswagen        sedan             four   9995.0
59     87        volvo        sedan             four  12940.0
60     88        volvo        wagon             four  13415.0

[61 rows x 5 columns]

In [27]:
# removing nan values in regard to a particular column
df.dropna(subset=['price'])

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
5,5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
7,9,bmw,sedan,101.2,NaN,ohc,four,NaN,23.0,16430.0
8,10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0
9,11,bmw,sedan,101.2,176.8,ohc,six,121.0,NaN,20970.0
10,13,bmw,sedan,103.5,189.0,ohc,six,NaN,16.0,30760.0
11,14,bmw,sedan,103.5,NaN,ohc,six,182.0,16.0,41315.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182.0,NaN,36880.0
13,16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
14,17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
15,18,chevrolet,sedan,NaN,158.8,ohc,four,70.0,NaN,6575.0
16,19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
17,20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
18,27,honda,wagon,96.5,NaN,ohc,four,76.0,30.0,7295.0
19,28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
20,29,honda,sedan,NaN,169.1,ohc,four,NaN,25.0,10345.0
21,30,isuzu,sedan,NaN,170.7,ohc,four,78.0,24.0,6785.0
24,33,jaguar,sedan,113.0,NaN,dohc,six,NaN,15.0,32250.0
25,34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
26,35,jaguar,sedan,NaN,191.7,ohcv,twelve,262.0,13.0,36000.0
27,36,mazda,hatchback,93.1,159.1,NaN,four,NaN,NaN,5195.0
28,37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
29,38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
30,39,mazda,hatchback,NaN,NaN,NaN,two,101.0,17.0,11845.0
31,43,mazda,sedan,104.9,175.0,ohc,four,NaN,NaN,18344.0
32,44,mercedes-benz,sedan,110.0,190.9,NaN,five,123.0,22.0,25552.0
33,45,mercedes-benz,wagon,NaN,190.9,ohc,five,123.0,22.0,28248.0
34,46,mercedes-benz,sedan,120.9,208.1,NaN,eight,184.0,14.0,40960.0
35,47,mercedes-benz,hardtop,112.0,199.2,NaN,eight,184.0,14.0,45400.0
36,49,mitsubishi,hatchback,NaN,157.3,ohc,four,NaN,37.0,5389.0
37,50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
38,51,mitsubishi,sedan,96.3,172.4,NaN,four,88.0,NaN,6989.0
39,52,mitsubishi,sedan,96.3,172.4,ohc,four,NaN,25.0,8189.0
40,53,nissan,sedan,NaN,NaN,ohc,four,55.0,NaN,7099.0
41,54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
42,55,nissan,sedan,NaN,165.3,ohc,four,69.0,31.0,6849.0
43,56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
44,57,nissan,sedan,100.4,184.6,ohcv,six,152.0,NaN,13499.0
45,61,porsche,hardtop,NaN,NaN,NaN,six,207.0,17.0,34028.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
48,66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
49,67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
50,68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
52,70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0
55,80,volkswagen,sedan,97.3,NaN,ohc,four,NaN,37.0,7775.0
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
57,82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
58,86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
59,87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [28]:
len(df.dropna(subset=['price']))

58