<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/dataset_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Shuffling dataset values: ```np.random.permutation()``` and ```df.take()```
  When we collect data, we may arrange it in a prticular order.
  
  But sometimes for research we need random values.
  
  So we need to shaffle the values in the dataset.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# uploading dataset and pre-processing it
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/housing_LR.csv')
df

      Unnamed: 0           district  rooms  size  level  max_levels    price
0              0       Юнусабадский      3  57.0      4           4  52000.0
1              1      Яккасарайский      2  52.0      4           5  56000.0
2              2       Чиланзарский      2  42.0      4           4  37000.0
3              3       Чиланзарский      3  65.0      1           4  49500.0
4              4       Чиланзарский      3  70.0      3           5  55000.0
...          ...                ...    ...   ...    ...         ...      ...
7273        7460        Яшнободский      1  38.0      5           5  24500.0
7274        7461        Яшнободский      2  49.0      1           4  32000.0
7275        7462    Шайхантахурский      2  64.0      3           9  40000.0
7276        7463  Мирзо-Улугбекский      1  18.0      1           4  11000.0
7277        7464       Чиланзарский      1  30.0      2           4  22914.0

[7278 rows x 7 columns]

In [3]:
df.columns

Index(['Unnamed: 0', 'district', 'rooms', 'size', 'level', 'max_levels',
       'price'],
      dtype='object')

In [5]:
df.rename(columns={'Unnamed: 0': 'id'}, inplace= True)

In [7]:
df.set_index('id', inplace= True)

In [18]:
# shaffling values
rand_idx = np.random.permutation(len(df))
rand_idx

array([4463, 6227, 6357, ..., 6761, 2583, 2958])

In [19]:
df.take(rand_idx)

             district  rooms   size  level  max_levels     price
id
4588     Юнусабадский      2   54.0      3           4   31000.0
6397      Мирабадский      4  150.0      3          12  140000.0
6530      Мирабадский      4   97.0      3           5   53972.0
2588      Учтепинский      2   58.0      3           9   33000.0
1530  Шайхантахурский      4   90.0      4           4   65000.0
...               ...    ...    ...    ...         ...       ...
5103    Яккасарайский      5  217.0      6           8  217000.0
5806      Мирабадский      2   62.0      4           4   53000.0
6942      Мирабадский      4  110.0      9           9   70500.0
2657  Шайхантахурский      2   54.0     11          12   34000.0
3037    Яккасарайский      2   55.0      4           5   47000.0

[7278 rows x 6 columns]

In [20]:
df

               district  rooms  size  level  max_levels    price
id
0          Юнусабадский      3  57.0      4           4  52000.0
1         Яккасарайский      2  52.0      4           5  56000.0
2          Чиланзарский      2  42.0      4           4  37000.0
3          Чиланзарский      3  65.0      1           4  49500.0
4          Чиланзарский      3  70.0      3           5  55000.0
...                 ...    ...   ...    ...         ...      ...
7460        Яшнободский      1  38.0      5           5  24500.0
7461        Яшнободский      2  49.0      1           4  32000.0
7462    Шайхантахурский      2  64.0      3           9  40000.0
7463  Мирзо-Улугбекский      1  18.0      1           4  11000.0
7464       Чиланзарский      1  30.0      2           4  22914.0

[7278 rows x 6 columns]

# Taking a particular number of random values as a sample:

In [21]:
df.sample(9) # not repetitive

               district  rooms  size  level  max_levels    price
id
4821    Шайхантахурский      4  80.0      2           4  75000.0
7069       Юнусабадский      2  60.0      4           4  40000.0
3679  Мирзо-Улугбекский      4  85.0      2           4  69990.0
3582       Чиланзарский      2  45.0      3           4  41000.0
4687       Юнусабадский      4  82.0      1           4  55000.0
2423        Учтепинский      2  45.0      1           4  35000.0
533         Яшнободский      1  40.0      5           8  13700.0
3610       Юнусабадский      3  70.0      1           4  78000.0
1049       Чиланзарский      2  46.0      2           4  32000.0

In [72]:
df_sample = df.sample(200, replace= True) # repetitive
df_sample

               district  rooms   size  level  max_levels    price
id
2505        Учтепинский      2   47.0      3           4  34500.0
2677       Чиланзарский      2   58.0      6           9  46000.0
3487       Чиланзарский      2   50.0      2           4  32999.0
1200        Учтепинский      1   34.0      4           4  24000.0
1853        Учтепинский      2   54.0      5           5  30000.0
...                 ...    ...    ...    ...         ...      ...
1031        Яшнободский      2   77.0      4           5  47000.0
7410  Мирзо-Улугбекский      2   50.0      4           4  39500.0
7446       Сергелийский      4  105.0      7           9  42000.0
2278        Олмазорский      3   70.0      6           7  57000.0
5234       Чиланзарский      2   47.0      1           4  43000.0

[200 rows x 6 columns]

In [73]:
len(df_sample.index.unique())

196