<a href="https://colab.research.google.com/github/elyorbek8/Introduction-to-Data-Science-ML-DL-and-AI./blob/main/data_grouping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Grouping values: ```df.groupby()```

In [36]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data.csv')
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [ ]:
df.company.value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
mercedes-benz    4
audi             4
volkswagen       4
mitsubishi       4
chevrolet        3
jaguar           3
isuzu            3
honda            3
porsche          3
alfa-romero      3
dodge            2
volvo            2
Name: count, dtype: int64

In [90]:
# grouping by a column
df.groupby('company').mean(numeric_only= True)

,index,wheel-base,length,horsepower,average-mileage,price
company,,,,,,
alfa-romero,1.00,90.566667,169.600000,125.333333,20.333333,15498.333333
audi,4.50,101.200000,180.800000,109.250000,20.000000,16392.500000
bmw,12.00,103.433333,185.033333,144.833333,19.000000,27213.333333
chevrolet,17.00,92.466667,151.933333,62.666667,41.000000,6007.000000
dodge,19.50,93.700000,157.300000,68.000000,31.000000,6303.000000
honda,28.00,96.500000,167.200000,92.333333,26.333333,10195.000000
isuzu,31.00,94.433333,160.833333,72.666667,33.333333,6785.000000
jaguar,34.00,109.333333,196.966667,204.666667,14.333333,34600.000000
mazda,38.60,95.900000,164.260000,75.400000,28.000000,9654.800000
mercedes-benz,45.50,113.225000,197.275000,153.500000,18.000000,35040.000000
mitsubishi,50.50,95.000000,164.850000,78.000000,29.500000,6689.000000
nissan,55.00,95.680000,170.140000,82.800000,31.400000,8289.000000
porsche,62.00,92.466667,171.166667,234.000000,17.000000,35528.000000
toyota,70.00,96.957143,167.571429,75.428571,28.714286,8216.857143
volkswagen,82.25,97.300000,171.700000,72.250000,31.750000,8435.000000
volvo,87.50,104.300000,188.800000,114.000000,23.000000,13177.500000

In [ ]:
df.groupby('company').price.mean()

company
alfa-romero      15498.333333
audi             16392.500000
bmw              27213.333333
chevrolet         6007.000000
dodge             6303.000000
honda            10195.000000
isuzu             6785.000000
jaguar           34600.000000
mazda             9654.800000
mercedes-benz    35040.000000
mitsubishi        6689.000000
nissan            8289.000000
porsche          35528.000000
toyota            8216.857143
volkswagen        8435.000000
volvo            13177.500000
Name: price, dtype: float64

In [ ]:
df.groupby('company').price.max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [ ]:
df.groupby('company').price.min()

company
alfa-romero      13495.0
audi             13950.0
bmw              16430.0
chevrolet         5151.0
dodge             6229.0
honda             7295.0
isuzu             6785.0
jaguar           32250.0
mazda             5195.0
mercedes-benz    25552.0
mitsubishi        5389.0
nissan            6649.0
porsche          34028.0
toyota            5348.0
volkswagen        7775.0
volvo            12940.0
Name: price, dtype: float64

In [ ]:
# grouping by several columns
df.groupby(['company', 'body-style']).mean(numeric_only= True)

                           index  wheel-base      length  horsepower  \
company       body-style
alfa-romero   convertible   0.50   88.600000  168.800000  111.000000
              hatchback     2.00   94.500000  171.200000  154.000000
audi          sedan         4.00   99.666667  176.833333  109.000000
              wagon         6.00  105.800000  192.700000  110.000000
bmw           sedan        12.00  103.433333  185.033333  144.833333
chevrolet     hatchback    16.50   91.450000  148.500000   59.000000
              sedan        18.00   94.500000  158.800000   70.000000
dodge         hatchback    19.50   93.700000  157.300000   68.000000
honda         sedan        28.50   96.500000  172.250000  100.500000
              wagon        27.00   96.500000  157.100000   76.000000
isuzu         sedan        31.00   94.433333  160.833333   72.666667
jaguar        sedan        34.00  109.333333  196.966667  204.666667
mazda         hatchback    37.50   93.650000  161.575000   76.250000
              sedan        43.00  104.900000  175.000000   72.000000
mercedes-benz hardtop      47.00  112.000000  199.200000  184.000000
              sedan        45.00  115.450000  199.500000  153.500000
              wagon        45.00  110.000000  190.900000  123.000000
mitsubishi    hatchback    49.50   93.700000  157.300000   68.000000
              sedan        51.50   96.300000  172.400000   88.000000
nissan        sedan        54.75   95.975000  170.125000   86.250000
              wagon        56.00   94.500000  170.200000   69.000000
porsche       convertible  62.00   89.500000  168.900000  207.000000
              hardtop      61.00   89.500000  168.900000  207.000000
              hatchback    63.00   98.400000  175.700000  288.000000
toyota        hatchback    67.00   95.700000  158.700000   62.000000
              wagon        72.25   97.900000  174.225000   85.500000
volkswagen    sedan        82.25   97.300000  171.700000   72.250000
volvo         sedan        87.00  104.300000  188.800000  114.000000
              wagon        88.00  104.300000  188.800000  114.000000

                           average-mileage         price
company       body-style
alfa-romero   convertible        21.000000  14997.500000
              hatchback          19.000000  16500.000000
audi          sedan              20.333333  15550.000000
              wagon              19.000000  18920.000000
bmw           sedan              19.000000  27213.333333
chevrolet     hatchback          42.500000   5723.000000
              sedan              38.000000   6575.000000
dodge         hatchback          31.000000   6303.000000
honda         sedan              24.500000  11645.000000
              wagon              30.000000   7295.000000
isuzu         sedan              33.333333   6785.000000
jaguar        sedan              14.333333  34600.000000
mazda         hatchback          27.250000   7482.500000
              sedan              31.000000  18344.000000
mercedes-benz hardtop            14.000000  45400.000000
              sedan              18.000000  33256.000000
              wagon              22.000000  28248.000000
mitsubishi    hatchback          34.000000   5789.000000
              sedan              25.000000   7589.000000
nissan        sedan              31.500000   8524.000000
              wagon              31.000000   7349.000000
porsche       convertible        17.000000  37028.000000
              hardtop            17.000000  34028.000000
              hatchback          17.000000           NaN
toyota        hatchback          32.333333   6058.000000
              wagon              26.000000   9836.000000
volkswagen    sedan              31.750000   8435.000000
volvo         sedan              23.000000  12940.000000
              wagon              23.000000  13415.000000

# Grouping values and applying aggregated (multiple) functions

In [82]:
df.columns

Index(['index', 'company', 'body-style', 'wheel-base', 'length', 'engine-type',
       'num-of-cylinders', 'horsepower', 'average-mileage', 'price'],
      dtype='object')

In [83]:
df.groupby('company').agg({
    'price': [min, max, np.mean]
})

<ipython-input-83-518db664591a>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('company').agg({
<ipython-input-83-518db664591a>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('company').agg({
<ipython-input-83-518db664591a>:1: FutureWarning: The provided callable <function mean at 0x7fec96841da0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('company').agg({

                 price
                   min      max          mean
company
alfa-romero    13495.0  16500.0  15498.333333
audi           13950.0  18920.0  16392.500000
bmw            16430.0  41315.0  27213.333333
chevrolet       5151.0   6575.0   6007.000000
dodge           6229.0   6377.0   6303.000000
honda           7295.0  12945.0  10195.000000
isuzu           6785.0   6785.0   6785.000000
jaguar         32250.0  36000.0  34600.000000
mazda           5195.0  18344.0   9654.800000
mercedes-benz  25552.0  45400.0  35040.000000
mitsubishi      5389.0   8189.0   6689.000000
nissan          6649.0  13499.0   8289.000000
porsche        34028.0  37028.0  35528.000000
toyota          5348.0  15750.0   8216.857143
volkswagen      7775.0   9995.0   8435.000000
volvo          12940.0  13415.0  13177.500000

In [91]:
numeric_cols = df.select_dtypes(include= 'number').columns
numeric_cols

Index(['index', 'wheel-base', 'length', 'horsepower', 'average-mileage',
       'price'],
      dtype='object')

In [92]:
df.groupby('company')[numeric_cols].agg([min, max, np.mean])

<ipython-input-92-4b88e64da48e>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('company')[numeric_cols].agg([min, max, np.mean])
<ipython-input-92-4b88e64da48e>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('company')[numeric_cols].agg([min, max, np.mean])
<ipython-input-92-4b88e64da48e>:1: FutureWarning: The provided callable <function mean at 0x7fec96841da0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('company')[numeric_cols].agg([min, max, np.mean])
<ipython-input-92-4b88e64da48e>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('company')[numeric_cols].agg([min, max, np.mean])

              index            wheel-base                    length         \
                min max   mean        min    max        mean    min    max
company
alfa-romero       0   2   1.00       88.6   94.5   90.566667  168.8  171.2
audi              3   6   4.50       99.4  105.8  101.200000  176.6  192.7
bmw               9  15  12.00      101.2  110.0  103.433333  176.8  197.0
chevrolet        16  18  17.00       88.4   94.5   92.466667  141.1  158.8
dodge            19  20  19.50       93.7   93.7   93.700000  157.3  157.3
honda            27  29  28.00       96.5   96.5   96.500000  157.1  175.4
isuzu            30  32  31.00       94.3   94.5   94.433333  155.9  170.7
jaguar           33  35  34.00      102.0  113.0  109.333333  191.7  199.6
mazda            36  43  38.60       93.1  104.9   95.900000  159.1  175.0
mercedes-benz    44  47  45.50      110.0  120.9  113.225000  190.9  208.1
mitsubishi       49  52  50.50       93.7   96.3   95.000000  157.3  172.4
nissan           53  57  55.00       94.5  100.4   95.680000  165.3  184.6
porsche          61  63  62.00       89.5   98.4   92.466667  168.9  175.7
toyota           66  79  70.00       95.7  104.5   96.957143  158.7  187.8
volkswagen       80  86  82.25       97.3   97.3   97.300000  171.7  171.7
volvo            87  88  87.50      104.3  104.3  104.300000  188.8  188.8

                          horsepower                  average-mileage      \
                     mean        min  max        mean             min max
company
alfa-romero    169.600000        111  154  125.333333              19  21
audi           180.800000        102  115  109.250000              18  24
bmw            185.033333        101  182  144.833333              15  23
chevrolet      151.933333         48   70   62.666667              38  47
dodge          157.300000         68   68   68.000000              31  31
honda          167.200000         76  101   92.333333              24  30
isuzu          160.833333         70   78   72.666667              24  38
jaguar         196.966667        176  262  204.666667              13  15
mazda          164.260000         68  101   75.400000              17  31
mercedes-benz  197.275000        123  184  153.500000              14  22
mitsubishi     164.850000         68   88   78.000000              25  37
nissan         170.140000         55  152   82.800000              19  45
porsche        171.166667        207  288  234.000000              17  17
toyota         167.571429         62  156   75.428571              19  35
volkswagen     171.700000         52  100   72.250000              26  37
volvo          188.800000        114  114  114.000000              23  23

                            price
                    mean      min      max          mean
company
alfa-romero    20.333333  13495.0  16500.0  15498.333333
audi           20.000000  13950.0  18920.0  16392.500000
bmw            19.000000  16430.0  41315.0  27213.333333
chevrolet      41.000000   5151.0   6575.0   6007.000000
dodge          31.000000   6229.0   6377.0   6303.000000
honda          26.333333   7295.0  12945.0  10195.000000
isuzu          33.333333   6785.0   6785.0   6785.000000
jaguar         14.333333  32250.0  36000.0  34600.000000
mazda          28.000000   5195.0  18344.0   9654.800000
mercedes-benz  18.000000  25552.0  45400.0  35040.000000
mitsubishi     29.500000   5389.0   8189.0   6689.000000
nissan         31.400000   6649.0  13499.0   8289.000000
porsche        17.000000  34028.0  37028.0  35528.000000
toyota         28.714286   5348.0  15750.0   8216.857143
volkswagen     31.750000   7775.0   9995.0   8435.000000
volvo          23.000000  12940.0  13415.0  13177.500000